let catalog = [
     {
          id: 0,
          title: "Xiaomi Earbuds Basic 2",
          price: 43,
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//5f7303737e3e0.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 1,
          title: "HUAWEI Band 6 (Black)",
          price: 57,
          img: "https://assets.asaxiy.uz/product/items/desktop/8f6…6954e8bb0161430c20210921120056797762oKaPgQSqy.jpg",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 3,
          title: "Apple iPhone 11 128 Gb, Black",
          price: 1105,
          img: "https://avatars.mds.yandex.net/get-mpic/4262452/img_id3167434503299217434.jpeg/orig",
          overview: "The functional and stylish smartphone Apple iPhone 11 in a metal case is able to provide not only everyday communication and entertainment, but also productive work. To do this, it is equipped with a powerful 6-core Apple A13 Bionic processor that supports the smooth operation of all components, as well as a 4 GB RAM module, which provides for quick switching between open applications and the ability to play games. The main (12; 12 Mp) and front (12 Mp) cameras will allow you to create photo masterpieces. The image on the screen of the Apple iPhone 11 smartphone with a diagonal of 6.1 inches has amazing detail and color reproduction. Oleophobic coating eliminates severe screen contamination. The case of the smartphone has a high degree of dust and moisture protection (IP68), which ensures efficient and long-term operation of the device. The non-removable 3110 mAh battery supports wireless charging, making the process easier and faster.",
          categories: ["phones", "apple"],
     },
     {
          id: 4,
          title: "Apple iPhone 12 mini 128 Gb, White",
          price: 998,
          img: "https://avatars.mds.yandex.net/get-mpic/5218438/img_id3284878141399346796.png/5hq",
          overview: "Apple iPhone 12 mini is a super-powerful smartphone in an ultra-small format. Inside the compact case, a whole set of advanced features has been registered. The lightning-fast A14 Bionic processor delivers incredible performance. The amazing Super Retina XDR display pleases with a juicy picture. The camera system surprises with image quality, and MagSafe charging eliminates the hassle of cables. Dolby Vision video recording is a strong trump card of the device. The stories are very realistic. You can edit videos directly on your gadget in the iMovie application. The Face ID recognition system works like clockwork. Apple iPhone 12 mini is a miniature smartphone with enormous functionality. This is the dynamic user's choice.",
          categories: ["phones", "apple"],
     },
     {
          id: 5,
          title: "Apple iPhone SE 2020 64 Gb",
          price: 412.35,
          img: "https://avatars.mds.yandex.net/get-mpic/5425309/img_id8041282677742130028.png/x248_trim",
          overview: "iPhone SE is the most powerful compact iPhone ever, packed with cutting-edge technologies. A13 Bionic is the fastest processor in the iPhone, delivering the best performance for apps, games and photography. Portrait mode and six lighting effects for studio-quality photos. Next-generation Smart HDR technology for incredible detail, even in bright and dark areas of the frame. Cinematic quality 4K video. And the most advanced features of iOS. With long battery life and water resistance, everything you love about iPhone comes in a surprisingly small package.",
          categories: ["phones", "apple"],
     },
     {
          id: 6,
          title: "Apple iPhone Xs",
          price: 574.97,
          img: "https://avatars.mds.yandex.net/get-mpic/1912364/img_id2264559175193642486.jpeg/x248_trim",
          overview: "iPhone XS features a 5.8-inch Super Retina HDR display. OLED panels provide the best color reproduction, deep blacks and impressive brightness. With improved FaceID technology, you can securely unlock your iPhone, sign in to your app accounts, and pay for purchases with just a glance. The A12 Bionic processor with next-generation Neural Engine uses machine learning technology to deliver incredible experiences for photography, gaming, augmented reality and more. And the stunning 12MP Dual Camera with Portrait mode, Portrait Lighting, enhanced bokeh and the all-new Depth feature gives you a whole new way to take portraits.",
          categories: ["phones", "apple"],
     },
     {
          id: 7,
          title: "Apple Macbook Pro Late 2021 ",
          price: 2423.58,
          img: "https://avatars.mds.yandex.net/get-marketpic/1583642/picbb1618e273a3278330e77f9bc0dbcb4f/120x160",
          overview: "The Apple MacBook Pro 14 (2021) is the most powerful MacBook Pro ever, powered by the high-tech M1 Pro chip. The memory bandwidth is more than 200 GB / s, and there is also the possibility of connecting two monitors. The MacBook Pro 14 (2021) features a stunning Liquid Retina XDR display with extreme dynamic range and superb contrast.",
          categories: ["computer", "apple"],
     },
     {
          id: 8,
          title: "Apple MacBook Pro 16",
          price: "3849.61",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "The new MacBook Pro is our most powerful laptop, built for world-changing and pushing the boundaries. With an impressive 16-inch Retina display, blazingly fast processor, next-generation graphics card, the highest battery life ever on a MacBook Pro, the new Magic Keyboard and massive storage, this is the best professional laptop for the most serious professional. Specs Type: laptop Operating system: macOS Processor Processor: Intel Core i7 9750H 2600 MHz Number of processor cores: 6 L3 cache: 12 MB Memory Memory: 16 GB DDR4 2666 MHz Image Screen: 16-inch, 3072x1920 widescreen Screen type: IPS Display Backlight: LED Graphics Card Type: Integrated, Discrete, Discrete, and Integrated Video Processor: AMD Radeon Pro 5300M Video Memory: 4 GB Video Memory Type: GDDR6 Storage Devices Drive Configuration: SSD Total Drive Capacity: 512 GB Optical Drive: No Connectivity Wireless: Wi-Fi IEEE 802.11ac, Bluetooth 5.0 Interfaces: Thunderbolt 3 x 4, microphone/headphones Combo Power Battery life: 11 hours Battery capacity: 100 Wh Battery type: Li-Pol Input devices Pointing devices: Touchpad Number of keyboard keys : 66 Keyboard backlight: yes Touch Bar: yes Sound Built-in speakers: yes Built-in subwoofer: yes Built-in microphone he: yes Optional Webcam: yes Fingerprint scanner: yes Features: metal case Dimensions (LxWxT): 357.9x245.9x16.2 mm Weight: 2 kg",
          categories: ["computer", "apple"],
     },
     {
          id: 9,
          title: "Apple MacBook Pro 13 Mid 2018",
          price: 1496.43,
          img: "https://avatars.mds.yandex.net/get-mpic/4393885/img_id8583047582289821123.jpeg/x248_trim",
          overview: "13.3 Laptop Apple MacBook Pro 13 Mid 2018 (2560x1600, Intel Core i5 2.3 GHz, RAM 8 GB, SSD 512 GB), MR9V2RU/A, silver",
          categories: ["computer", "apple"],
     },
     {
          id: 10,
          title: "16 ASUS StudioBook H7600HM",
          price: 3017.93,
          img: "https://avatars.mds.yandex.net/get-mpic/5245452/img_id2242488603442486682.jpeg/7hq",
          overview: "16, 3840x2400, 2.40кг, Windows 11 Pro",
          categories: ["computer", "asus"],
     },
     {
          id: 9,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 9,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 10,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 11,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 12,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 13,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 14,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 15,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
]