let catalog = [
     {
          id: 0,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//5f7303737e3e0.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 1,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 2,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 3,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 4,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 5,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 6,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 7,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 8,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 9,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 10,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 11,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 12,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 13,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 14,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 15,
          title: "Xiaomi Earbuds Basic 2",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
]